### ISSUE TITLE
Try huge CSS selectors instead of javascript loops

### ISSUE THREAD

**Issue by jesus2099** [jesus2099/konami-command#119]
```css
a[href*='/artist/mbid1], a[href*='/artist/mbid2], a[href*='/artist/mbid3], …,
a[href*='/release/mbid4], a[href*='/release/mbid5], a[href*='/release/mbid6], …,
a[href*='/release-group/mbid7], a[href*='/release-group/mbid8], a[href*='/release-group/mbid9], …, {
	bla-bla: highlight-style-here;
}
```

And compare the performance on a huge page (build a static example if necessary).
Someone told me Firefox could be very slow with big CSS selectors but I think the problem was with very selective selectors, here it’s rather wide than selective.
This way, no need to do funny stuff for all the AJAX added links.
